{{- if .Values.rbac.create -}}
{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "filebeat.fullname" . }}
  annotations:
{{- if .Values.podSecurityPolicy.annotations }}
{{ toYaml .Values.podSecurityPolicy.annotations | indent 4 }}
{{- end }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - pathPrefix: /var/log
      readOnly: true
    - pathPrefix: /var/lib/docker/containers
      readOnly: true
    - pathPrefix: {{ .Values.data.hostPath }}
  requiredDropCapabilities:
    - ALL
  volumes:
{{- range .Values.podSecurityPolicy.volumes }}
    - {{ . }}
{{- end }}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: {{ .Values.podSecurityPolicy.runAsUser.rule }}
{{- if .Values.podSecurityPolicy.runAsUser.ranges }}
    ranges:
      - min: {{ .Values.podSecurityPolicy.runAsUser.ranges.min }}
        max: {{ .Values.podSecurityPolicy.runAsUser.ranges.max }}
{{- end }}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  hostPorts:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
{{- end -}}
{{- end -}}
